#!/bin/bash

dbquery(){ mysql -D maaatch -u maaatch_admin --password=uoGeikeen9Iyie9Miefo -e "$@"; }

for table in $(dbquery "show tables;" -sN); do
    echo -e "\n---- $table:"
    dbquery "explain $table;"
done
